server:
  port: 0

spring:
  application:
    name: shopping-cart

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/commerce_shopping_cart
    username: dbuser
    password: 12345

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

order:
  api:
    prefix: /api/v1/order

ShoppingCart:
  api:
    prefix: /api/v1/cart

