spring:
  application:
    name: payment
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 6000
      discovery:
        enabled: true
        serviceId: config-server
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO

resilience4j:
  circuitbreaker:
    instances:
      order:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
