spring:
  application:
    name: shopping-cart
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 6000
      discovery:
        enabled: true
        serviceId: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 0
resilience4j:
  circuitbreaker:
    instances:
      warehouse:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s